<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="16" passed="10" failed="6" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2021-07-28T13:27:25 IST" name="Suite" finished-at="2021-07-28T13:40:09 IST" duration-ms="764599">
    <groups>
    </groups>
    <test started-at="2021-07-28T13:27:25 IST" name="Test" finished-at="2021-07-28T13:40:09 IST" duration-ms="764599">
      <class name="com.saucedemo.testcases.TC_StandardUser_AddToCart">
        <test-method is-config="true" signature="setup()[pri:0, instance:com.saucedemo.testcases.TC_StandardUser_AddToCart@2ea227af]" started-at="2021-07-28T13:29:38 IST" name="setup" finished-at="2021-07-28T13:29:42 IST" duration-ms="3997" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="Login_StandardUser()[pri:0, instance:com.saucedemo.testcases.TC_StandardUser_AddToCart@2ea227af]" started-at="2021-07-28T13:29:42 IST" name="Login_StandardUser" description="Verify whether the Standard user is able add products into cart" finished-at="2021-07-28T13:30:30 IST" duration-ms="48599" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Login_StandardUser -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.saucedemo.testcases.TC_StandardUser_AddToCart@2ea227af]" started-at="2021-07-28T13:30:30 IST" name="tearDown" finished-at="2021-07-28T13:30:31 IST" duration-ms="1196" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.saucedemo.testcases.TC_StandardUser_AddToCart -->
      <class name="com.saucedemo.testcases.TC_StandardUser_RemovingAndAddingInCart">
        <test-method is-config="true" signature="setup()[pri:0, instance:com.saucedemo.testcases.TC_StandardUser_RemovingAndAddingInCart@363ee3a2]" started-at="2021-07-28T13:31:28 IST" name="setup" finished-at="2021-07-28T13:31:32 IST" duration-ms="4491" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="StandardUser_Removing()[pri:0, instance:com.saucedemo.testcases.TC_StandardUser_RemovingAndAddingInCart@363ee3a2]" started-at="2021-07-28T13:31:32 IST" name="StandardUser_Removing" description="Verify whether the Standard user is able add multiple products into cart and remove" finished-at="2021-07-28T13:32:22 IST" duration-ms="49327" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- StandardUser_Removing -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.saucedemo.testcases.TC_StandardUser_RemovingAndAddingInCart@363ee3a2]" started-at="2021-07-28T13:32:22 IST" name="tearDown" finished-at="2021-07-28T13:32:23 IST" duration-ms="1434" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.saucedemo.testcases.TC_StandardUser_RemovingAndAddingInCart -->
      <class name="com.saucedemo.testcases.TC_ProblemUser_AddToCartMultiple">
        <test-method is-config="true" signature="setup()[pri:0, instance:com.saucedemo.testcases.TC_ProblemUser_AddToCartMultiple@79b06cab]" started-at="2021-07-28T13:33:05 IST" name="setup" finished-at="2021-07-28T13:33:08 IST" duration-ms="3037" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="ProblemUser()[pri:0, instance:com.saucedemo.testcases.TC_ProblemUser_AddToCartMultiple@79b06cab]" started-at="2021-07-28T13:33:08 IST" name="ProblemUser" description="Verify whether the Problem  is able add multiple products into cart" finished-at="2021-07-28T13:33:42 IST" duration-ms="33999" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Cart count is not matching expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Cart count is not matching expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at com.saucedemo.pageObjects.Saucedemo_HomePage.verify_cartCount(Saucedemo_HomePage.java:238)
at com.saucedemo.testcases.TC_ProblemUser_AddToCartMultiple.ProblemUser(TC_ProblemUser_AddToCartMultiple.java:52)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1507)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ProblemUser -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.saucedemo.testcases.TC_ProblemUser_AddToCartMultiple@79b06cab]" started-at="2021-07-28T13:33:42 IST" name="tearDown" finished-at="2021-07-28T13:33:43 IST" duration-ms="1331" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.saucedemo.testcases.TC_ProblemUser_AddToCartMultiple -->
      <class name="com.saucedemo.testcases.TC_Entitlement_LockedOutUser">
        <test-method is-config="true" signature="setup()[pri:0, instance:com.saucedemo.testcases.TC_Entitlement_LockedOutUser@4ddced80]" started-at="2021-07-28T13:28:06 IST" name="setup" finished-at="2021-07-28T13:28:09 IST" duration-ms="2973" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="Login_LockedOutUser()[pri:0, instance:com.saucedemo.testcases.TC_Entitlement_LockedOutUser@4ddced80]" started-at="2021-07-28T13:28:09 IST" name="Login_LockedOutUser" description="Verify whether the Locked Out user is able not to login" finished-at="2021-07-28T13:28:12 IST" duration-ms="3415" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Login_LockedOutUser -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.saucedemo.testcases.TC_Entitlement_LockedOutUser@4ddced80]" started-at="2021-07-28T13:28:12 IST" name="tearDown" finished-at="2021-07-28T13:28:13 IST" duration-ms="1476" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.saucedemo.testcases.TC_Entitlement_LockedOutUser -->
      <class name="com.saucedemo.testcases.TC_ProblemUser_RemovingAndAddingInCart">
        <test-method is-config="true" signature="setup()[pri:0, instance:com.saucedemo.testcases.TC_ProblemUser_RemovingAndAddingInCart@3eb7fc54]" started-at="2021-07-28T13:33:43 IST" name="setup" finished-at="2021-07-28T13:33:46 IST" duration-ms="3161" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="Problemuser_Removing()[pri:0, instance:com.saucedemo.testcases.TC_ProblemUser_RemovingAndAddingInCart@3eb7fc54]" started-at="2021-07-28T13:33:46 IST" name="Problemuser_Removing" description="Verify whether the Problem user is able add multiple products into cart and remove" finished-at="2021-07-28T13:34:20 IST" duration-ms="34000" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Not Matching expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Not Matching expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at com.saucedemo.pageObjects.Saucedemo_Cart.verify_SelectedProductsAreShowing(Saucedemo_Cart.java:55)
at com.saucedemo.testcases.TC_ProblemUser_RemovingAndAddingInCart.Problemuser_Removing(TC_ProblemUser_RemovingAndAddingInCart.java:57)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1507)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Problemuser_Removing -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.saucedemo.testcases.TC_ProblemUser_RemovingAndAddingInCart@3eb7fc54]" started-at="2021-07-28T13:34:20 IST" name="tearDown" finished-at="2021-07-28T13:34:22 IST" duration-ms="1456" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.saucedemo.testcases.TC_ProblemUser_RemovingAndAddingInCart -->
      <class name="com.saucedemo.testcases.TC_ProblemUser_AddToCart">
        <test-method is-config="true" signature="setup()[pri:0, instance:com.saucedemo.testcases.TC_ProblemUser_AddToCart@4690b489]" started-at="2021-07-28T13:32:23 IST" name="setup" finished-at="2021-07-28T13:32:26 IST" duration-ms="3016" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="Login_ProblemUser()[pri:0, instance:com.saucedemo.testcases.TC_ProblemUser_AddToCart@4690b489]" started-at="2021-07-28T13:32:26 IST" name="Login_ProblemUser" description="Verify whether the Problem user is able add products into cart" finished-at="2021-07-28T13:33:03 IST" duration-ms="37489" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[driver.findElement(text_error).getText() expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: driver.findElement(text_error).getText() expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at com.saucedemo.pageObjects.Saucedemo_CheckOut.verify_ErrorMsg(Saucedemo_CheckOut.java:58)
at com.saucedemo.testcases.TC_ProblemUser_AddToCart.Login_ProblemUser(TC_ProblemUser_AddToCart.java:67)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1507)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Login_ProblemUser -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.saucedemo.testcases.TC_ProblemUser_AddToCart@4690b489]" started-at="2021-07-28T13:33:04 IST" name="tearDown" finished-at="2021-07-28T13:33:05 IST" duration-ms="1098" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.saucedemo.testcases.TC_ProblemUser_AddToCart -->
      <class name="com.saucedemo.testcases.TC_Entitlement_PerformanceGlitchUser">
        <test-method is-config="true" signature="setup()[pri:0, instance:com.saucedemo.testcases.TC_Entitlement_PerformanceGlitchUser@1534f01b]" started-at="2021-07-28T13:28:13 IST" name="setup" finished-at="2021-07-28T13:28:17 IST" duration-ms="3150" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="Login_StandardUser()[pri:0, instance:com.saucedemo.testcases.TC_Entitlement_PerformanceGlitchUser@1534f01b]" started-at="2021-07-28T13:28:17 IST" name="Login_StandardUser" description="Verify whether the Performance Glitch user is able to login successfuly" finished-at="2021-07-28T13:28:58 IST" duration-ms="41505" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Login_StandardUser -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.saucedemo.testcases.TC_Entitlement_PerformanceGlitchUser@1534f01b]" started-at="2021-07-28T13:28:58 IST" name="tearDown" finished-at="2021-07-28T13:28:59 IST" duration-ms="1182" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.saucedemo.testcases.TC_Entitlement_PerformanceGlitchUser -->
      <class name="com.saucedemo.testcases.TC_Entitlement_StandardUser">
        <test-method is-config="true" signature="setup()[pri:0, instance:com.saucedemo.testcases.TC_Entitlement_StandardUser@65466a6a]" started-at="2021-07-28T13:27:25 IST" name="setup" finished-at="2021-07-28T13:27:30 IST" duration-ms="4806" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="Login_StandardUser()[pri:0, instance:com.saucedemo.testcases.TC_Entitlement_StandardUser@65466a6a]" started-at="2021-07-28T13:27:30 IST" name="Login_StandardUser" description="Verify whether the Standard user is able to login successfuly" finished-at="2021-07-28T13:28:04 IST" duration-ms="34013" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Login_StandardUser -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.saucedemo.testcases.TC_Entitlement_StandardUser@65466a6a]" started-at="2021-07-28T13:28:04 IST" name="tearDown" finished-at="2021-07-28T13:28:06 IST" duration-ms="1262" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.saucedemo.testcases.TC_Entitlement_StandardUser -->
      <class name="com.saucedemo.testcases.TC_NegativeCase_CheckOut">
        <test-method is-config="true" signature="setup()[pri:0, instance:com.saucedemo.testcases.TC_NegativeCase_CheckOut@1184ab05]" started-at="2021-07-28T13:37:42 IST" name="setup" finished-at="2021-07-28T13:37:45 IST" duration-ms="3152" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="StandardUser_CheckOut_NC()[pri:0, instance:com.saucedemo.testcases.TC_NegativeCase_CheckOut@1184ab05]" started-at="2021-07-28T13:37:45 IST" name="StandardUser_CheckOut_NC" description="Verify whether the checkout page is accepting invalid/empty values." finished-at="2021-07-28T13:38:50 IST" duration-ms="64678" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Error Message is not Showing expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Error Message is not Showing expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at com.saucedemo.pageObjects.Saucedemo_CheckOut.verify_CheckOutErrorMsg(Saucedemo_CheckOut.java:74)
at com.saucedemo.testcases.TC_NegativeCase_CheckOut.StandardUser_CheckOut_NC(TC_NegativeCase_CheckOut.java:127)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1507)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- StandardUser_CheckOut_NC -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.saucedemo.testcases.TC_NegativeCase_CheckOut@1184ab05]" started-at="2021-07-28T13:38:50 IST" name="tearDown" finished-at="2021-07-28T13:38:51 IST" duration-ms="1214" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.saucedemo.testcases.TC_NegativeCase_CheckOut -->
      <class name="com.saucedemo.testcases.TC_Entitlement_ProblemUser">
        <test-method is-config="true" signature="setup()[pri:0, instance:com.saucedemo.testcases.TC_Entitlement_ProblemUser@78e117e3]" started-at="2021-07-28T13:28:59 IST" name="setup" finished-at="2021-07-28T13:29:02 IST" duration-ms="2892" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="Login_StandardUser()[pri:0, instance:com.saucedemo.testcases.TC_Entitlement_ProblemUser@78e117e3]" started-at="2021-07-28T13:29:02 IST" name="Login_StandardUser" description="Verify whether the Problem user is able to login successfuly" finished-at="2021-07-28T13:29:36 IST" duration-ms="34097" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Login_StandardUser -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.saucedemo.testcases.TC_Entitlement_ProblemUser@78e117e3]" started-at="2021-07-28T13:29:36 IST" name="tearDown" finished-at="2021-07-28T13:29:38 IST" duration-ms="1330" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.saucedemo.testcases.TC_Entitlement_ProblemUser -->
      <class name="com.saucedemo.testcases.TC_NegativeCase_EmptyCart">
        <test-method is-config="true" signature="setup()[pri:0, instance:com.saucedemo.testcases.TC_NegativeCase_EmptyCart@3aefe5e5]" started-at="2021-07-28T13:38:51 IST" name="setup" finished-at="2021-07-28T13:38:54 IST" duration-ms="3321" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="EmptyCart()[pri:0, instance:com.saucedemo.testcases.TC_NegativeCase_EmptyCart@3aefe5e5]" started-at="2021-07-28T13:38:54 IST" name="EmptyCart" description="Verify whether the user is able proceed order without adding products into cart" finished-at="2021-07-28T13:40:08 IST" duration-ms="73272" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Cart is Empty expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Cart is Empty expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at com.saucedemo.pageObjects.Saucedemo_Cart.click_checkOut(Saucedemo_Cart.java:25)
at com.saucedemo.testcases.TC_NegativeCase_EmptyCart.EmptyCart(TC_NegativeCase_EmptyCart.java:58)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1507)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- EmptyCart -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.saucedemo.testcases.TC_NegativeCase_EmptyCart@3aefe5e5]" started-at="2021-07-28T13:40:08 IST" name="tearDown" finished-at="2021-07-28T13:40:09 IST" duration-ms="1467" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.saucedemo.testcases.TC_NegativeCase_EmptyCart -->
      <class name="com.saucedemo.testcases.TC_StandadUser_AddToCartMultiple">
        <test-method is-config="true" signature="setup()[pri:0, instance:com.saucedemo.testcases.TC_StandadUser_AddToCartMultiple@4386f16]" started-at="2021-07-28T13:30:31 IST" name="setup" finished-at="2021-07-28T13:30:36 IST" duration-ms="4914" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="StandardUser_Multiple()[pri:0, instance:com.saucedemo.testcases.TC_StandadUser_AddToCartMultiple@4386f16]" started-at="2021-07-28T13:30:36 IST" name="StandardUser_Multiple" description="Verify whether the Standard user is able add multiple products into cart" finished-at="2021-07-28T13:31:26 IST" duration-ms="50058" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- StandardUser_Multiple -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.saucedemo.testcases.TC_StandadUser_AddToCartMultiple@4386f16]" started-at="2021-07-28T13:31:26 IST" name="tearDown" finished-at="2021-07-28T13:31:28 IST" duration-ms="1253" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.saucedemo.testcases.TC_StandadUser_AddToCartMultiple -->
      <class name="com.saucedemo.testcases.TC_NegativeCase_Login">
        <test-method is-config="true" signature="setup()[pri:0, instance:com.saucedemo.testcases.TC_NegativeCase_Login@47d90b9e]" started-at="2021-07-28T13:37:35 IST" name="setup" finished-at="2021-07-28T13:37:38 IST" duration-ms="3439" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="Login_StandardUser()[pri:0, instance:com.saucedemo.testcases.TC_NegativeCase_Login@47d90b9e]" started-at="2021-07-28T13:37:38 IST" name="Login_StandardUser" description="Verify whether the Fields accepting invalid values" finished-at="2021-07-28T13:37:41 IST" duration-ms="2602" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Epic sadface: Username and password do not match any user in this service expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Epic sadface: Username and password do not match any user in this service expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at com.saucedemo.pageObjects.Saucedemo_Login.verify_ErrorMsg(Saucedemo_Login.java:61)
at com.saucedemo.testcases.TC_NegativeCase_Login.Login_StandardUser(TC_NegativeCase_Login.java:23)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1507)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Login_StandardUser -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.saucedemo.testcases.TC_NegativeCase_Login@47d90b9e]" started-at="2021-07-28T13:37:41 IST" name="tearDown" finished-at="2021-07-28T13:37:42 IST" duration-ms="1360" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.saucedemo.testcases.TC_NegativeCase_Login -->
      <class name="com.saucedemo.testcases.TC_PerformanceGlitchUser_AddToCart">
        <test-method is-config="true" signature="setup()[pri:0, instance:com.saucedemo.testcases.TC_PerformanceGlitchUser_AddToCart@7f552bd3]" started-at="2021-07-28T13:34:22 IST" name="setup" finished-at="2021-07-28T13:34:25 IST" duration-ms="3374" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="Login_PerformanceGlitchUser()[pri:0, instance:com.saucedemo.testcases.TC_PerformanceGlitchUser_AddToCart@7f552bd3]" started-at="2021-07-28T13:34:25 IST" name="Login_PerformanceGlitchUser" description="Verify whether the Performance Glitch user is able add products into cart" finished-at="2021-07-28T13:35:24 IST" duration-ms="58776" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Login_PerformanceGlitchUser -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.saucedemo.testcases.TC_PerformanceGlitchUser_AddToCart@7f552bd3]" started-at="2021-07-28T13:35:24 IST" name="tearDown" finished-at="2021-07-28T13:35:25 IST" duration-ms="1524" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.saucedemo.testcases.TC_PerformanceGlitchUser_AddToCart -->
      <class name="com.saucedemo.testcases.TC_PerformanceGlitchUser_AddToCartMultiple">
        <test-method is-config="true" signature="setup()[pri:0, instance:com.saucedemo.testcases.TC_PerformanceGlitchUser_AddToCartMultiple@3c22fc4c]" started-at="2021-07-28T13:35:25 IST" name="setup" finished-at="2021-07-28T13:35:29 IST" duration-ms="3902" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="PerformaceGlitchUser()[pri:0, instance:com.saucedemo.testcases.TC_PerformanceGlitchUser_AddToCartMultiple@3c22fc4c]" started-at="2021-07-28T13:35:29 IST" name="PerformaceGlitchUser" description="Verify whether the Performance Glitch user is able add products into cart" finished-at="2021-07-28T13:36:28 IST" duration-ms="59132" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- PerformaceGlitchUser -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.saucedemo.testcases.TC_PerformanceGlitchUser_AddToCartMultiple@3c22fc4c]" started-at="2021-07-28T13:36:28 IST" name="tearDown" finished-at="2021-07-28T13:36:30 IST" duration-ms="1530" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.saucedemo.testcases.TC_PerformanceGlitchUser_AddToCartMultiple -->
      <class name="com.saucedemo.testcases.TC_PerformanceGlitchUser_RemovingAndAddingInCart">
        <test-method is-config="true" signature="setup()[pri:0, instance:com.saucedemo.testcases.TC_PerformanceGlitchUser_RemovingAndAddingInCart@460d0a57]" started-at="2021-07-28T13:36:30 IST" name="setup" finished-at="2021-07-28T13:36:33 IST" duration-ms="2736" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="PerformanceGlitchUser_Removing()[pri:0, instance:com.saucedemo.testcases.TC_PerformanceGlitchUser_RemovingAndAddingInCart@460d0a57]" started-at="2021-07-28T13:36:33 IST" name="PerformanceGlitchUser_Removing" description="Verify whether the PerformanceGlitch user is able add multiple products into cart and remove" finished-at="2021-07-28T13:37:33 IST" duration-ms="60590" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- PerformanceGlitchUser_Removing -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.saucedemo.testcases.TC_PerformanceGlitchUser_RemovingAndAddingInCart@460d0a57]" started-at="2021-07-28T13:37:33 IST" name="tearDown" finished-at="2021-07-28T13:37:35 IST" duration-ms="1403" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.saucedemo.testcases.TC_PerformanceGlitchUser_RemovingAndAddingInCart -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
